### ISSUE TITLE
Runtime error in rdiscount ('no_superscript' missing)

### ISSUE THREAD

**Issue by woutgg** [apjanke/ronn-ng#26]
When running ronn, it exits with the error that `no_superscript` is not defined (see below for the error and stacktrace.)
I found #5, and noticed that the missing function was only introduced in rdiscount version 2.1.6 (as per [here](https://github.com/davidfstr/rdiscount/blob/master/CHANGELOG.md#version-216-may-28-2013)). So I'm guessing this is simply a matter of updating the dependency version.

```
ronn -r --pipe --date=2018-03-01 man-page.1.ronn > man-page.1
Traceback (most recent call last):
        11: from /usr/local/Cellar/ronn-ng/0.8.0/libexec/bin/ronn:23:in `<main>'
        10: from /usr/local/Cellar/ronn-ng/0.8.0/libexec/bin/ronn:23:in `load'
         9: from /usr/local/Cellar/ronn-ng/0.8.0/libexec/gems/ronn-ng-0.8.0/bin/ronn:183:in `<top (required)>'
         8: from /usr/local/Cellar/ronn-ng/0.8.0/libexec/gems/ronn-ng-0.8.0/bin/ronn:183:in `map'
         7: from /usr/local/Cellar/ronn-ng/0.8.0/libexec/gems/ronn-ng-0.8.0/bin/ronn:183:in `block in <top (required)>'
         6: from /usr/local/Cellar/ronn-ng/0.8.0/libexec/gems/ronn-ng-0.8.0/bin/ronn:183:in `new'
         5: from /usr/local/Cellar/ronn-ng/0.8.0/libexec/gems/ronn-ng-0.8.0/lib/ronn/document.rb:80:in `initialize'
         4: from /usr/local/Cellar/ronn-ng/0.8.0/libexec/gems/ronn-ng-0.8.0/lib/ronn/document.rb:208:in `sniff'
         3: from /usr/local/Cellar/ronn-ng/0.8.0/libexec/gems/ronn-ng-0.8.0/lib/ronn/document.rb:208:in `new'
         2: from /usr/local/Cellar/ronn-ng/0.8.0/libexec/gems/rdiscount-2.0.7/lib/rdiscount.rb:93:in `initialize'
         1: from /usr/local/Cellar/ronn-ng/0.8.0/libexec/gems/rdiscount-2.0.7/lib/rdiscount.rb:93:in `each'
/usr/local/Cellar/ronn-ng/0.8.0/libexec/gems/rdiscount-2.0.7/lib/rdiscount.rb:93:in `block in initialize': undefined method `no_superscript=' for #<RDiscount:0x00007ff5da144650> (NoMethodError)
```

**Comment by apjanke** [comment]
I think your analysis is right. However, we're looking at migrating from rdiscount to kramdown to support jruby (#28), so this may be a moot issue soon.

**Comment by apjanke** [comment]
We've migrated to kramdown, so this should be fixed now. Please re-open if this issue crops up again.
