### ISSUE TITLE
Crash if using mini_portile2 version 2.5.0

### ISSUE THREAD

**Issue by judaew** [apjanke/ronn-ng#63]
The MacPorts repository has mini_portile2 version 2.5.0. If version 2.4.0 is missing, ronn-ng crashes.

Is version 2.4.0 mandatory, or is it possible to upgrade to 2.5.0? And if so, how can this be done? I don't understand Ruby projects, so I tried to raise the version in Germfile.lock, but apparently, the version is being set somewhere else.

At startup, I have the following log:

```shell
Traceback (most recent call last):
	12: from /opt/local/bin/ronn-2.7:23:in `<main>'
	11: from /opt/local/lib/ruby2.7/2.7.0/rubygems.rb:295:in `activate_bin_path'
	10: from /opt/local/lib/ruby2.7/2.7.0/rubygems.rb:295:in `synchronize'
	 9: from /opt/local/lib/ruby2.7/2.7.0/rubygems.rb:296:in `block in activate_bin_path'
	 8: from /opt/local/lib/ruby2.7/2.7.0/rubygems/specification.rb:1373:in `activate'
	 7: from /opt/local/lib/ruby2.7/2.7.0/rubygems/specification.rb:1391:in `activate_dependencies'
	 6: from /opt/local/lib/ruby2.7/2.7.0/rubygems/specification.rb:1391:in `each'
	 5: from /opt/local/lib/ruby2.7/2.7.0/rubygems/specification.rb:1405:in `block in activate_dependencies'
	 4: from /opt/local/lib/ruby2.7/2.7.0/rubygems/specification.rb:1373:in `activate'
	 3: from /opt/local/lib/ruby2.7/2.7.0/rubygems/specification.rb:1391:in `activate_dependencies'
	 2: from /opt/local/lib/ruby2.7/2.7.0/rubygems/specification.rb:1391:in `each'
	 1: from /opt/local/lib/ruby2.7/2.7.0/rubygems/specification.rb:1402:in `block in activate_dependencies'
/opt/local/lib/ruby2.7/2.7.0/rubygems/dependency.rb:313:in `to_specs': Could not find 'mini_portile2' (~> 2.4.0) - did find: [mini_portile2-2.5.0] (Gem::MissingSpecVersionError)
Checked in 'GEM_PATH=/Users/judaew/.gem/ruby/2.7.0:/opt/local/lib/ruby2.7/gems/2.7.0', execute `gem env` for more information
```

https://github.com/macports/macports-ports/pull/9116

[gem-env.txt](https://github.com/apjanke/ronn-ng/files/5541709/gem-env.txt)

**Comment by judaew** [comment]
I apologize for disturbing you. Because I am not good at ruby projects, I thought that the problem was in `ronn-ng`. Later I discovered that the problem was related to the `nokogiri` dependency on which `ronn-ng` depends. It's OK now.
