### ISSUE TITLE
HTML-style comment causes RuntimeError

### ISSUE THREAD

**Issue by nabijaczleweli** [apjanke/ronn-ng#65]
```
nabijaczleweli@babtop:/tmp$ cat owo.md
There exists no other user-land tool for decrypting this. <!-- (TODO: make an LD_PRELOADable for extracting the key maybe) -->
nabijaczleweli@babtop:/tmp$ ronn owo.md
     roff: ./owo
Traceback (most recent call last):
        21: from /usr/bin/ronn:196:in `<main>'
        20: from /usr/bin/ronn:196:in `each'
        19: from /usr/bin/ronn:211:in `block in <main>'
        18: from /usr/bin/ronn:211:in `each'
        17: from /usr/bin/ronn:221:in `block (2 levels) in <main>'
        16: from /usr/lib/ruby/vendor_ruby/ronn/document.rb:243:in `convert'
        15: from /usr/lib/ruby/vendor_ruby/ronn/document.rb:248:in `to_roff'
        14: from /usr/lib/ruby/vendor_ruby/ronn/document.rb:248:in `new'
        13: from /usr/lib/ruby/vendor_ruby/ronn/roff.rb:18:in `initialize'
        12: from /usr/lib/ruby/vendor_ruby/ronn/roff.rb:95:in `block_filter'
        11: from /usr/lib/ruby/vendor_ruby/ronn/roff.rb:92:in `block_filter'
        10: from /usr/lib/ruby/vendor_ruby/nokogiri/xml/node_set.rb:237:in `each'
         9: from /usr/lib/ruby/vendor_ruby/nokogiri/xml/node_set.rb:237:in `upto'
         8: from /usr/lib/ruby/vendor_ruby/nokogiri/xml/node_set.rb:238:in `block in each'
         7: from /usr/lib/ruby/vendor_ruby/ronn/roff.rb:92:in `block in block_filter'
         6: from /usr/lib/ruby/vendor_ruby/ronn/roff.rb:124:in `block_filter'
         5: from /usr/lib/ruby/vendor_ruby/ronn/roff.rb:247:in `inline_filter'
         4: from /usr/lib/ruby/vendor_ruby/nokogiri/xml/node_set.rb:237:in `each'
         3: from /usr/lib/ruby/vendor_ruby/nokogiri/xml/node_set.rb:237:in `upto'
         2: from /usr/lib/ruby/vendor_ruby/nokogiri/xml/node_set.rb:238:in `block in each'
         1: from /usr/lib/ruby/vendor_ruby/ronn/roff.rb:247:in `block in inline_filter'
/usr/lib/ruby/vendor_ruby/ronn/roff.rb:305:in `inline_filter': unexpected node: #<Nokogiri::XML::Comment:0x2f8 " (TODO: make an LD_PRELOADable for extracting the key maybe) "> (RuntimeError)
```

**Comment by apjanke** [comment]
Yep, that's a Ronn bug. Should be an easy fix.

**Comment by apjanke** [comment]
Fixed in https://github.com/apjanke/ronn-ng/commit/cbf6330e381c03ee40ad560d6072a5857e71a86b, I think. HTML/XML comments are now ignored when producing roff output.

```
[ronn-ng] $ cat owo.md
There exists no other user-land tool for decrypting this. <!-- (TODO: make an LD_PRELOADable for extracting the key maybe) -->

[ronn-ng] $ bundle exec ronn owo.md
     roff: ./owo
     html: ./owo.html                                            +man
[ronn-ng] $ cat owo
.\" generated with Ronn-NG/v0.10.0
.\" http://github.com/apjanke/ronn-ng/tree/0.10.0-SNAPSHOT
.TH "OWO" "" "December 2020" ""
.SH "NAME"
\fBowo\fR
.P
There exists no other user\-land tool for decrypting this\.
[ronn-ng] $
```

Look good to you?

**Comment by nabijaczleweli** [comment]
Yes, that's what I'd expect it to behave like. Thanks!
